### ISSUE TITLE
test.py is not working

### ISSUE THREAD

**Issue by sorasful** [JaesungHuh/voice-gender-classifier#1]
Hi there ! 

I'm trying to test out your repository which looks really great, but when I try to run the example `test.py` I do get : 

RuntimeError: Couldn't find appropriate backend to handle uri data/00001.wav and format None.

Don't you have this error ? Maybe it's because of the version you are using ?

**Comment by JaesungHuh** [comment]
Hi sorasful,

I reinstalled the python environment and it works fine for me.

Could you share the exact error message if possible?

You could also refer to this link : https://github.com/facebookresearch/demucs/issues/570#issuecomment-2319948557

**Comment by sorasful** [comment]
Hmm, actually you are right!  After some research it seems that my list of available backend in empty and it's due to the way I installed FFMPEG or the others.

It has nothing to do with your repository, my mistake. Hope it can help someone with the same error.
Closing this.
