### ISSUE TITLE
 a Tensor with 2 elements cannot be converted to Scalar

### ISSUE THREAD

**Issue by AuYuHui** [JaesungHuh/voice-gender-classifier#3]
音频如果有多种声音报错
If there are multiple sounds in the audio, an error message will be generated

能不能支持多种声音识别，只返回最高概率的
Can it support multiple voice recognition and only return the highest probability

**Comment by JaesungHuh** [comment]
Hi AuYuHui,

Sorry but it doesn't support if multiple voices exist in the audio. It'll return the probability but it's hard to interpret the result.

The model only assumes there is only one voice in the audio.
